name: flowdock-rest
version: 0.1.0.0
synopsis: Flowdock REST API
description: |
  Bindings to the <https://www.flowdock.com/api/rest Flowdock REST API>.

  Currently there are only non-destructive operations.
  Also not all types are written out.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-flowdock-rest
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md
- fixtures/*.json

ghc-options: -Wall

dependencies:
  - base                  >=4.7   && <4.9
  - aeson                 >=0.8   && <0.10
  - ansi-wl-pprint        >=0.6   && <0.7
  - binary                >=0.7   && <0.8
  - binary-orphans        >=0.1.1 && <0.2
  - binary-tagged         >=0.1.1 && <0.2
  - bytestring            >=0.10  && <0.11
  - deepseq               >=1.3   && <1.5
  - exceptions            >=0.8   && <0.9
  - generics-sop          >=0.1   && <0.2
  - hashable              >=1.2   && <1.3
  - http-client           >=0.4   && <0.5
  - http-client-tls       >=0.2   && <0.3
  - lens                  >=4.7   && <4.13
  - semigroups            >=0.16  && <0.17
  - tagged                >=0.7   && <0.9
  - time                  >=1.4   && <1.6
  - text                  >=1.2   && <1.3
  - unordered-containers  >=0.2   && <0.3

library:
  source-dirs: src

tests:
  flowdock-rest-test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - flowdock-rest
      - tasty                 >=0.10  && <0.12
      - tasty-quickcheck      >=0.8   && <0.9
      - file-embed            >=0.0.9
