name: flowdock-rest-cli
version: 0.0.0.0
synopsis: Example cli tool for flowdock-rest
description: Bindings to Flowdock REST api.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-flowdock-rest
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.7 && <4.9
  - aeson
  - aeson-pretty
  - ansi-wl-pprint
  - base64-bytestring
  - bytestring
  - deepseq
  - directory
  - exceptions
  - hashable >= 1.2
  - http-client
  - http-client-tls
  - lens
  - monad-http
  - tagged
  - text
  - optparse-applicative
  - transformers
  - flowdock-rest == 0.0.0.0

executables:
  flowdock-rest-cli:
    main: Main.hs
    source-dirs: src
